### ISSUE TITLE
_check_n_features has moved

### ISSUE THREAD

**Issue by SaravananSathyanandhaQC** [Quantco/glum#835] opened 2024-09-09 14:42 UTC
As of Thursday, [this PR](https://github.com/scikit-learn/scikit-learn/pull/29696) moved from `sklearn.base.BaseEstimator` to `sklearn.utils.validation`. This will then cause [this line](https://github.com/Quantco/glum/blob/0873560455cdd78b1b975ed7bb683d5ddfa5cc42/src/glum/_glm.py#L2506) to break when the next sklearn release comes

**Comment by lbittarello** [comment] 2024-09-09 14:46
Duplicate of #830. :)

**Closed by lbittarello** 2024-09-09 14:46 UTC
